[project]
name = "flaskr"
version = "1.0.0"
description = "Mix de noticias random"
dependencies = [
  "flask",
  "bs4",
  "requests",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
