DROP TABLE IF EXISTS user;
DROP TABLE IF EXIST regional;
CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE regional (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  event TEXT NOT NULL,
  url TEXT NOT NULL,
  direction TEXT NOT NULL
);
